name: penguins
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.2+9
  path_provider: ^2.1.5
  path: ^1.9.1
  http: ^1.3.0
  camera_android: ^0.10.10
  flutter_scalable_ocr: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
